### ISSUE TITLE
RaiMan from SikuliX

### ISSUE THREAD

**Issue by RaiMan** [GielRaijmakers/FTAS#1]
questions:
- what do you think are the advantages of your solution against such things like RobotFramework or Cucumber?
- It seems you are relying on the existence of some SikuliX installation, that is used, to run your stuff. Is it based on the features of version 1.1.0?
- you have your own screenshot feature. why?

about the license:
- MIT License, should be packed with the jars in the new versions

It would be nice (but not recommended) if you have some pointers to http://sikulix.com in your docs, when talking about SikuliX

**Comment by GielRaijmakers** [comment]
Hi RainMan. 
1: The advantage of this above Cucumber or Robot is that the tester doens't have to have any technical knowledge. Also, I automate the objects, not a testscript. If an object is "automated" is can be used in 100 different scripts, at all time. The functional tests made by the tester never have to change, I only need to change an object. 

2: Yes, I use 1.1.0, I will mention it in the documentation. Not sure if I use specific functions from 1.1.0. 

3: No, I don't have a screenshot feature. I make the screenshots in Sikuli. These screenshots are stored in a "repository script". 

The documentation is very undercontrstuction. I can image that not all is clear when you read the current documentation. I asked about the license so I can keep it in mind from the start.

**Comment by RaiMan** [comment]
at 1: making reusable whatever is also supported in those frameworks. But the tester itself might not be the one who creates these reusable entities, due to lack of scripting/progarmming knowledge.

... but since I cannot not yet see/understand what you mean by "automating objects", which might be available for reuse in whatever testing environment, I will wait and watch your further development.

at 2: you should not do any compromises: base your solution on 1.1.0, so that it can only be used with 1.1.0+

at 3: generic.rb/ScreenShot ??

If you ever have any specific question, bug or feature request: do not hesitate to contact me.
